edit_uri: ""
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      user: br3ndonland
      repo: crp
      repo_url_shorthand: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - "index.md"
repo_name: br3ndonland/crp
repo_url: https://github.com/br3ndonland/crp
site_name: crp docs
site_url: ""
theme:
  favicon: assets/images/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.top
  font: false
  icon:
    logo: octicons/image-24
    repo: octicons/mark-github-24
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      accent: deep purple
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      accent: deep purple
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
use_directory_urls: false
